/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Delivery;

import Business.EcoSystem;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author patel
 */
public class DeliveryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    public DeliveryJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        VRButton = new javax.swing.JButton();
        VDjButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(0, 128, 128));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome Delivery Partner");

        VRButton.setBackground(new java.awt.Color(0, 128, 128));
        VRButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        VRButton.setForeground(new java.awt.Color(255, 255, 255));
        VRButton.setText("View Requests");
        VRButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        VRButton.setBorderPainted(false);
        VRButton.setContentAreaFilled(false);
        VRButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VRButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VRButtonMouseExited(evt);
            }
        });
        VRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VRButtonActionPerformed(evt);
            }
        });

        VDjButton.setBackground(new java.awt.Color(0, 128, 128));
        VDjButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        VDjButton.setForeground(new java.awt.Color(255, 255, 255));
        VDjButton.setText("View Details");
        VDjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        VDjButton.setBorderPainted(false);
        VDjButton.setContentAreaFilled(false);
        VDjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VDjButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VDjButtonMouseExited(evt);
            }
        });
        VDjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VDjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(VRButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(VDjButton)
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VRButton)
                    .addComponent(VDjButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VRButtonActionPerformed
        DeliveryRequestJPanel drJPanel=new DeliveryRequestJPanel(userProcessContainer,business);
        jSplitPane1.setBottomComponent(drJPanel);
    }//GEN-LAST:event_VRButtonActionPerformed

    private void VRButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VRButtonMouseEntered
          VRButton.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_VRButtonMouseEntered

    private void VRButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VRButtonMouseExited
        VRButton.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_VRButtonMouseExited

    private void VDjButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VDjButtonMouseEntered
    VDjButton.setForeground(Color.black);         // TODO add your handling code here:
    }//GEN-LAST:event_VDjButtonMouseEntered

    private void VDjButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VDjButtonMouseExited
      VDjButton.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_VDjButtonMouseExited

    private void VDjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VDjButtonActionPerformed
        DeliveryDetailsJPanel ddJPanel=new DeliveryDetailsJPanel(userProcessContainer,business);
        jSplitPane1.setBottomComponent(ddJPanel);
    }//GEN-LAST:event_VDjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VDjButton;
    private javax.swing.JButton VRButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
